### ISSUE TITLE
DiDeMo test queries seem to not include all captions

### ISSUE THREAD

**Issue by reddyav1** [ruc-aimc-lab/TeachCLIP#2]
I have a question regarding the text queries in the DiDeMo test set. 

In your provided flie `data/datasets/didemo/QuerySet/test-query.txt` I see that only a single caption appears for each video. In your paper (and in others using DiDeMo for video retrieval), the problem is typically formulated as paragraph-video retrieval by concatenating all captions for the video into one text query. Could you shed some light on this and clarify under which setting your results are reported?

And thank you for sharing the code and splits/annotations! It's very helpful.

**Comment by RuixiangZhao** [comment]
Hi,

Thank you for your observation regarding the captions in the `data/datasets/didemo/QuerySet/test-query.txt` file. You are correct that it contains only a single caption per video.

Please accept our apologies for any confusion this may have caused. **The results on DiDeMo presented in our paper were achieved using the paragraph-video retrieval setting**, where each video is associated with a concatenated paragraph of all its captions. This discrepancy arose due to an oversight when releasing the codebase.

During the release process, we updated the way the test data is loaded, but unfortunately, an error was introduced that resulted in the new `data/datasets/didemo/QuerySet/test-query.txt` file containing only one caption per video. The previous data loading process, which reads all captions from `data/datasets/didemo/Annotations/test_data.json`, can be found [here](https://github.com/ruc-aimc-lab/TeachCLIP/blob/fc4d54a873b5b7e445582862950d3df5e445f58d/dataloaders/dataloader_didemo_retrieval.py#L58).

We appreciate your correction and **have now updated the `data/datasets/didemo/QuerySet/test-query.txt`** file to include the correct format.

Thank you again for your feedback!

Best regards,  
Ruixiang

**Comment by reddyav1** [comment]
Great! Thank you.

**Comment by reddyav1** [comment]
Great! Thank you.
